spring:
  datasource:
    hikari:
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        cache:
          use_second_level_cache: false
        temp:
          use_jdbc_metadata_defaults: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  config: classpath:logback-spring.xml

server:
  port: ${PORT}

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 86400000  # 24 hours


bot:
  token: ${TELEGRAM_TOKEN}
  username: ${TELEGRAM_USERNAME}